### ISSUE TITLE
Unify criteria when creating BidderSeatBid object whether is built by HttpBidderRequester or HttpAdapterRequester

### ISSUE THREAD

**Issue by jordillachmrf** [rubicon-project/prebid-server-java#144]
While testing/debuging I came across a difference between how HttpBidderRequester and HttpAdapterRequester create BidderSeatBid objects.
The former creates it in its method toBidderSeatBid (using errors method) and aside from BidderBid's errors it ALSO takes into account HttpCall s errors, while the later (HttpAdapterRequester) in its method toBidderSeatBid only takes into account BidderBid's errors, and not AdapterResponse's BidderStatus/timedOut info

Actually I am not sure if this could be considered a bug or not, but I think that this difference worth creating an issue

**Comment by schernysh** [comment]
Since all bidders were implemented natively there is no need in HttpAdapterRequester anymore, it has been removed in #241.

@jordillachmrf if you think this is not an issue anymore I'll close it.
