### ISSUE TITLE
VendorListService should also take into account legIntPurposeIds

### ISSUE THREAD

**Issue by jordillachmrf** [rubicon-project/prebid-server-java#153]
VendorListService should also take into account legIntPurposeIds otherwise with the current vendor list version https://vendorlist.consensu.org/v-107/vendorlist.json there is no chance to create a BidderRequest (ExchangeService.makeBidderRequests) that contain user's buyeruid info or device info.

Having said that I've realized that some SSPs, like for instance **Index**, only has purpose 3 in featureIds section :|

**Comment by jordillachmrf** [comment]
As stated in https://github.com/rubicon-project/prebid-server-java/blob/master/docs/developers/PrebidServerJava_GDPR_Requirements.pdf --  Instead of looking specifically for Purpose 3 the server needs to look for whatever purposes are declared in the vendorlist

**Comment by rpanchyk** [comment]
Implemented in https://github.com/rubicon-project/prebid-server-java/pull/175
