### ISSUE TITLE
TLS/SSL support

### ISSUE THREAD

**Issue by vinnybod** [rubicon-project/prebid-server-java#180]
I've added the option for ssl in our fork at: https://github.com/freestarcapital/prebid-server-java/pull/4/files . Is this something anyone would be interested in having in the main project? If so, I will open a pull request.

**Comment by schernysh** [comment]
Thanks for suggestion.
While in most practical cases prebid-server is expected to run behind a load-balancer and it is natural to offload SSL/TLS termination to it, having SSL/TLS support in prebid-server itself definitely won't hurt. Please feel free to open a PR for this.
