### ISSUE TITLE
how to run this project

### ISSUE THREAD

**Issue by wushuang123** [rubicon-project/prebid-server-java#264]
I can not run this project, Could you help me?

**Comment by schernysh** [comment]
Hello and welcome.

Relevant instructions for configuring and running Prebid Server are located in [docs](https://github.com/rubicon-project/prebid-server-java/blob/master/docs) directory, in particular [run](https://github.com/rubicon-project/prebid-server-java/blob/master/docs/run.md) and [config](https://github.com/rubicon-project/prebid-server-java/blob/master/docs/config.md) guides. [Config-app](https://github.com/rubicon-project/prebid-server-java/blob/master/docs/config-app.md) contains detailed description of configuration properties supported by the Prebid Server.

**Comment by wushuang123** [comment]
Thank you
