### ISSUE TITLE
Add a flag to configure whether AMP cache will be populated with winning bids only

### ISSUE THREAD

**Issue by mikiescolarmrf** [rubicon-project/prebid-server-java#279]
In order to decide what bids have to be cached or not, a nice to have feature could be a flag to store only winning bids. This was an existing behaviour in the past and we think it could be interesting to recover it.

To activate this feature, we could add `auction.cache.only-winning-bids` (or similar) as a new execution parameter when launching the JVM. In addition to this, we could also be able to change configuration file properly.

**Comment by bretg** [comment]
I'm  ok with the general idea, but request the following changes:

if ext.prebid.cache.winningonly is true, then cache only the top bid
unless ext.prebid.targeting.includebidderkeys is true, in which case includebidderkeys takes precedence and winningonly should be ignored.

**Comment by rpanchyk** [comment]
As a proposal:
Can we add a new key to the bid request `ext.prebid.cache.winningonly` to control a response not from configuration but from input request?

Example request:
```
{
  ...
  "ext": {
    "prebid": {
      "cache": {
        "winningonly": true,
        "bids": {...},
        "vastxml": {...}
      }
    }
  }
  ...
}
```

**Comment by bretg** [comment]
This gets into the old "config-vs-request" debate.

Am open to hearing the case for config. Would it be that a PBS host company decides to only ever cache the top bid -- therefore denying their client publishers the ability to use ext.prebid.targeting.includebidderkeys ?

Adding @jordillachmrf

**Comment by mikiescolarmrf** [comment]
@rpanchyk, in a shared environment we think this could be the right way (using request), but in our case we only need a widely solution (using configuration).

@bretg, sure... but answering your question... our proposal wouldn't affect other features or any other ways to configure PBS or to restrict publishers in any way.

**Comment by bretg** [comment]
> our proposal wouldn't affect other features or any other ways to configure PBS or to restrict publishers in any way.

Sorry, but that's incorrect. Caching only the winning bid invalidates the `includebidderkeys` feature. This may be fine for a given host company, but needs to be explicit.

Here's a proposal - let's discuss config-vs-request this Friday in the Prebid Server PMC -- hopefully @jordillachmrf can be there to discuss.

**Comment by bretg** [comment]
Discussed with @jordillachmrf today in the Prebid Server meeting - we agreed that putting this flag in the request would be a good way avoid the `includebidderkeys` conflict, but putting the power to create and resolve that conflict in client hands.

**Comment by mikiescolarmrf** [comment]
> @mikiescolarmrf - we discussed in todays committee meeting. I did a quick scan through this code and am not seeing it considering the state of ext.prebid.targeting.includebidderkeys as noted in the issue:
> 
> ```
> if ext.prebid.cache.winningonly is true, then cache only the top bid
> unless ext.prebid.targeting.includebidderkeys is true, in which case includebidderkeys takes precedence and winningonly should be ignored.
> ```
> 
> And there ought to be a couple of additional unit tests that cover the interaction of these two settings.

@bretg sure... we are agree with you... `ext.prebid.targeting.includebidderskeys` should take precedence over other restrictions on results caching. 

On the other hand, just to confirm the final decision, the agreement was to put the flag in the request, or in the configuration?

In any case, would you mind if we open a new PR and close the previous one?

**Comment by bretg** [comment]
I don't feel strongly about where this config exists. Re-reading the thread, sounds like we agreed that it was fine to leave on the request.

**Comment by RossGoncharuk** [comment]
Submitted a new PR #484 with the flag in request and `ext.prebid.targeting.includebidderskeys` checking.

**Comment by RossGoncharuk** [comment]
Updated PR with the changes discussed with @rpanchyk and @bretg - added support for both configuration property `auction.cache.only-winning-bids` and request field `ext.prebid.cache.winningonly` with latest having a higher priority. 

`includebidderskeys` feature still takes precedence, regardless of `winningonly` source.

**Comment by rpanchyk** [comment]
PR #484 is merged to master. Closing.
Please, open new issue if any changes needed.
