### ISSUE TITLE
Enable compression between PBS and bidders

### ISSUE THREAD

**Issue by mikiescolarmrf** [rubicon-project/prebid-server-java#288]
We have found that Vert.x HttpClient supports compression in responses. We think that we could configure BasicHttpClient to use this feature.

Once activated, we expect a performance improvement between PBS and bidders.

BTW, do you think this feature should be configurable?

**Comment by rpanchyk** [comment]
Thank you for bringing it up, @mikiescolarmrf !
It's a cool feature and we can enable it in [HttpClientOptions](https://vertx.io/docs/apidocs/io/vertx/core/http/HttpClientOptions.html#setTryUseCompression-boolean-) for HttpClient.

While sending the request HttpClient will check this option and add `accept-encoding` header.
From `vertx-core-3.6.2-sources.jar!/io/vertx/core/http/impl/Http1xClientConnection.java`:
```
if (conn.options.isTryUseCompression() && request.headers().get(ACCEPT_ENCODING) == null) {
  // if compression should be used but nothing is specified by the user support deflate and gzip.
  request.headers().set(ACCEPT_ENCODING, DEFLATE_GZIP);
}
```

To be PBS flexible, we think it should be configurable, like `http-client.use-compression` with `true|false` values available.
