### ISSUE TITLE
Set E-Plannning's vendor id

### ISSUE THREAD

**Issue by albertmolinermrf** [rubicon-project/prebid-server-java#310]
E-Planning's adapter has 0 as its vendor's id, while it should be 90 (Teroa S.A.).

Additionally:
- When there aren't active campaigns, responses contain null lists that have to be gently handled.
- If a parameter ct=1 is not present in the adapter's request, a redirection to a URL with the missing parameter happens.
- When an ad units lacks name in the bid request, the request is properly generated but the bid extraction fails.

**Comment by rpanchyk** [comment]
PR #311 merged to master. Closing.
