### ISSUE TITLE
Allow following HTTP redirections

### ISSUE THREAD

**Issue by albertmolinermrf** [rubicon-project/prebid-server-java#316]
org.prebid.server.vertx.http.BasicHttpClient is not following redirections (HTTP status code 30x). This behaviour is probably fine in the general scenario, but some SSPs (eg, eplanning) sometimes do return redirections when bidding.

Therefore, the ability to enable them should be configurable.

**Comment by rpanchyk** [comment]
Thanks, merged to master. Closing.
