### ISSUE TITLE
Multisize and stored requests in AMP

### ISSUE THREAD

**Issue by albertmolinermrf** [rubicon-project/prebid-server-java#345]
In Pubmatic, each ad slot has a fixed size inside its id. For example, "123456@300x600" corresponds to an ad slot of width 300 and height 600.

Our stored requests for AMP contain all the supported bidders in `imp[0].ext`. For example (only the relevant fragments provided):

```
{
  "id": "tag_id",
  "imp": [
    {
      "id": "1",
      "banner": {
        "format": [
          {
            "w": 300,
            "h": 600
          },
          {
            "w": 300,
            "h": 250
          },
          {
            "w": 320,
            "h": 50
          }
        ]
      },
      "ext": {
        "rubicon": {
          "placementId": 99999
        },
        "pubmatic": {
          "publisherId": "11111",
          "adSlot": "123456@300x600"
        }
      }
    }
  ]
}
```
Each AMP page knows which sizes fit in each of its placements, and add the proper `ms` parameter to each /openrtb2/amp call. For the sake of simplicity, only `ms` will be mentioned below, but the same applies to sibling parameters like `oh`, `h`, etc. For example:
```
https://.../openrtb2/amp?tag_id=tag_id&ms=300x250,320x50
```
Upon receiving this call, Prebid Server is retrieving the stored request above, which includes all three formats and the Pubmatic `ext` because the ApplicationSettings interface does not offer hinting which sizes are being requested. This should not be a problem, because the `format` values are properly overwritten if the `ms` parameter is provided.

However, the Pubmatic adapter is using the `adslot` attribute to generate a bid request like this (only relevant fragment provided):

```
{
  "id": "tag_id",
  "imp": [
    {
      "id": "1",
      "banner": {
        "format": [
          {
            "w": 300,
            "h": 250
          },
          {
            "w": 320,
            "h": 50
          }
        ],
        "w": 300,
        "h": 600
      },
      "tagId": "123456"
    }
  ]
}
```
So, the `format` does contain the suitable values from the `ms` parameter, but the unsuitable size from the ad slot id. Pubmatic is ignoring the sizes in `format` and caring only about the banner's width and height, which leads to 300x600 creativities being displayed in positions where only 300x250 or 320x50 are expected.

Should different stored requests be created for slots supporting each set of sizes (ie, one stored request for 300x600, 300x250 and 320x50, another for 300x250 and 320x50, another for 300x600 and 300x250, and so on for all possible combinations)? Leaving aside the scalability concerns, than what would be the purpose of the `ms` parameter?

Or perhaps Prebid Server should have some kind of control, like for example discarding bid requests provided by adapters if `format` and `w`/`h` do not match?

This following comment by Mike Chowla may be relevant: https://github.com/prebid/Prebid.js/pull/3618#issuecomment-471123682

**Comment by mike-chowla** [comment]
The PubMatic bidder in both versions of Prebid Server currently sets the primary size from the ‘@<width>x<height>’ appended to the adSlot parameter.    Unfortunately, ‘@<width>x<height>’ is currently required or the PubMatic adapter fails validation the request.

I have it the PubMatic dev team’s backlog to remove the requirement to specify width and heigh on the ad slot.  We’ll get this done on Go version first.  Java version might take us a little longer because the dev team PubMatic hasn’t worked on the Java version before.

**Comment by mike-chowla** [comment]
I'm not sure it's worth changing the core to deal with something the adapter isn't getting right since the issue will be resolved once we fix the adapter.  There's also several cases of Prebid.js adapters that change sizes in what they request from their backend because their ads takeover the page theme or otherwise not standard IAB sizes.

**Comment by albertmolinermrf** [comment]
If the adapter is to be changed, I agree that dealing with this kind of cases in the core might be overkill.

Do you have an estimation of when it can be addressed? Just something approximate.

**Comment by pm-deepak-dhage** [comment]
PR [#357](/rubicon-project/prebid-server-java/pull/357) raised to fix this issue.

**Comment by pm-deepak-dhage** [comment]
PR is merged to master. 
@albertmolinermrf, with this change, you will have to make some changes in PubMatic request parameters to remove the size from the ad slot name. Just to make sure there is no confusion, "adSlot": "123456@300x600" from stored request you have shared should be changed to "adSlot": "123456".

**Comment by albertmolinermrf** [comment]
Thank you very much.

Just to clarify the behaviour:

> [If size is not present,] first size from the format (ad_units.sizes) array will be picked as primary size

Does this mean that _only_ the first size from the format will be considered, ignoring all the others? Or that it will be prioritized, but any other size could be returned?

**Comment by pm-deepak-dhage** [comment]
All sizes are considered. 
Priority is given to banner.h and banner.w to get the matching platform specific ID of SSP (like ad tag ID and site ID for PubMatic, placement ID for AppNexus etc), but all sizes are passed in request and any among the other sizes could be returned in response.

**Comment by albertmolinermrf** [comment]
Many thanks for the clarification!
