### ISSUE TITLE
MaxMindGeoLocationService database specified as GeoLite2-City.mmdb while tar file from maxmind contains country file

### ISSUE THREAD

**Issue by renjith4** [rubicon-project/prebid-server-java#556]
Not sure whether this is intentional or a bug. 
while starting the server, the following error comes up

```
2019-12-03 16:02:42.182  INFO 92129 --- [ntloop-thread-3] o.p.server.execution.RemoteFileSyncer    : Existing file /var/tmp/prebid/GeoLite2-Country.tar.gz cant be processed by service, try to download after removal
io.vertx.core.impl.NoStackTraceThrowable: Database file GeoLite2-City.mmdb not found in /var/tmp/prebid/GeoLite2-Country.tar.gz archive
ERROR 92129 --- [ntloop-thread-3] o.p.server.execution.RemoteFileSyncer    : Service cant process file /var/tmp/prebid/GeoLite2-Country.tar.gz and still unavailable.
```

Looking into the issue
MaxMindGeoLocationService has got database specified as GeoLite2-City.mmdb while tar file from maxmind is the country db

1. https://github.com/rubicon-project/prebid-server-java/blob/0307690bf0b608767857e3813e5b838bedfdf4d3/src/main/java/org/prebid/server/geolocation/MaxMindGeoLocationService.java#L31
2. https://github.com/rubicon-project/prebid-server-java/blob/30e872b0f1f79de2caa85ecf1929b544adf22671/src/main/resources/application.yaml#L92

```
prebid> wget https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz
2019-12-03 16:10:29 (10.1 MB/s) - GeoLite2-Country.tar.gz saved [2031113/2031113]
➜  prebid> tar -xvf GeoLite2-Country.tar.gz
x GeoLite2-Country_20191126/
x GeoLite2-Country_20191126/LICENSE.txt
x GeoLite2-Country_20191126/COPYRIGHT.txt
x GeoLite2-Country_20191126/GeoLite2-Country.mmdb
```

Changing to `private static final String DATABASE_FILE_NAME = "GeoLite2-Country.mmdb";` brings up the server without any errors.  

Is this intentional?

**Comment by DGarbar** [comment]
Thanks for noticing that. [FIX](https://github.com/rubicon-project/prebid-server-java/pull/557)

**Comment by renjith4** [comment]
Cool. Closing the issue
