### ISSUE TITLE
Maxmind database name

### ISSUE THREAD

**Issue by albertmolinermrf** [rubicon-project/prebid-server-java#575]
The [default URL](https://github.com/rubicon-project/prebid-server-java/blob/master/src/main/resources/application.yaml) of the geolocation database is `https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz`. On the other hand, [the name of the file looked for in the code](https://github.com/rubicon-project/prebid-server-java/blob/master/src/main/java/org/prebid/server/geolocation/MaxMindGeoLocationService.java) is `GeoLite2-City.mmdb`.
Is the mismatch (`Country` vs. `City`) intended? Isn't it causing that no geolocation database is effectively loaded at runtime?

**Comment by DGarbar** [comment]
Thanks for contributing.

This issue already fixed 
https://github.com/rubicon-project/prebid-server-java/pull/557

**Comment by albertmolinermrf** [comment]
Thanks!

Are there plans to merge it?

**Comment by rpanchyk** [comment]
Merged to the `master` branch. Closing.
