### ISSUE TITLE
Add influxDb tags

### ISSUE THREAD

**Issue by michae1** [rubicon-project/prebid-server-java#613]
Sometimes influxDb tags can come in handy to split data by region, hostname etc. 
I find there is no tagging in current prebid-server-java.
As [dropwizard-metrics-influxdb](https://github.com/iZettle/dropwizard-metrics-influxdb) already has tags support, I suggest this simple implementation.

PR: #615

**Comment by rpanchyk** [comment]
Thanks. PR is merged. Closing.
