### ISSUE TITLE
Settings for optimal performance 

### ISSUE THREAD

**Issue by EdwinliTitech** [rubicon-project/prebid-server-java#890]
Hi there,
The default configs for rubicon adapter
[https://github.com/rubicon-project/prebid-server-java/blob/master/src/main/resources/bidder-config/rubicon.yaml](url)
have an endpoint starts with exapi-us-east, and since we are bidding from Japan, I'm curious about where can I get the settings I need for optimal performance with rubicon's adapter? 
Thanks.

**Comment by rpanchyk** [comment]
Hi @EdwinliTitech !
You can set `https://exapi-apac.rubiconproject.com/a/api/exchange.json?tk_sdc=apac` endpoint for Japan.

Also, you can always reach out account information from globalsupport@magnite.com
Thanks!
